name: IMG
version: 0.1.1
date: 02/01/2014
description: Computations with iterated monodromy groups

authors:
    - name: Laurent Bartholdi
      url: http://www.uni-math.gwdg.de/laurent

maintainers:
    - name: Laurent Bartholdi
      url: http://www.uni-math.gwdg.de/laurent

GAP: ">=4.6.0"

needed-pkgs:
    - name: "FR"
      version: ">=2.0.0"
      url: "https://gap-packages.github.io/FR"
    - name: "GAPDoc"
      version: ">=1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

suggested-pkgs:
    - name: "Float"
      version: ">=0.4"
      url: "http://gap-packages.github.io/float/"

www: http://laurentbartholdi.github.com/img/
readme: README.img
packageinfo: http://laurentbartholdi.github.com/img/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/laurentbartholdi/img/archive/0.1.1.tar.gz

abstract: The <span class="pkgname">IMG</span> package allows    GAP to manipulate iterated monodromy groups

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
